version: 2.1

orbs:
   node: circleci/node@4.1


jobs:   
  test:
     working_directory: ~/build-and-test3
     docker:
      - image: cimg/node:15.1
   
    steps:
      - checkout     
      - node/install-packages    
      - run:
          name: Run tests
          command: npm test

workflows: 
  sample:
    jobs:
      - test
